[tool.poetry]
name = "gzy-backend"
version = "0.1.0"
description = ""
authors = ["colaftc <colaftc@126.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.0"
pillow = "^10.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
