# Generated by Django 5.0 on 2023-12-18 10:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GZY', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ('index', '-created_at'), 'verbose_name': 'Menu', 'verbose_name_plural': 'Menu'},
        ),
        migrations.AlterModelOptions(
            name='menucategory',
            options={'ordering': ('index', '-created_at'), 'verbose_name_plural': 'Menu Categories'},
        ),
        migrations.AddField(
            model_name='menu',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='index',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Index'),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menucategory',
            name='index',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Index'),
        ),
    ]
