# Generated by Django 5.0 on 2023-12-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GZY', '0002_alter_menu_options_alter_menucategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Visible'),
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Visible'),
        ),
    ]
