# Generated by Django 5.0 on 2023-12-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GZY', '0004_remove_menu_category_delete_menucategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='page_type',
            field=models.IntegerField(choices=[(1, '产品页'), (2, '自定义页'), (3, '文章页')], default=3, verbose_name='Page Type'),
        ),
    ]
