# Generated by Django 5.0 on 2023-12-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GZY', '0006_custompage_product_productcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Main Image'),
        ),
    ]
