# Generated by Django 5.0 on 2023-12-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GZY', '0008_alter_product_main_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_img',
            field=models.ImageField(blank=True, null=True, upload_to='static/upload/', verbose_name='Main Image'),
        ),
    ]
