# Generated by Django 5.0 on 2023-12-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GZY', '0009_alter_product_main_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Visible'),
        ),
    ]
