# Generated by Django 5.0 on 2023-12-20 05:55

import GZY.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GZY', '0010_product_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_img',
            field=models.ImageField(upload_to=GZY.models.product_image_path_and_filename, verbose_name='Main Image'),
        ),
    ]
