# Generated by Django 5.0 on 2023-12-20 06:03

import GZY.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GZY', '0011_alter_product_main_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetailImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=GZY.models.product_detail_image_path_and_filename, verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GZY.product', verbose_name='Product')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
