# Generated by Django 5.0 on 2023-12-20 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GZY', '0012_productdetailimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detail_images', to='GZY.productcategory', verbose_name='Category'),
        ),
    ]
