# Generated by Django 5.0 on 2023-12-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GZY', '0013_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdetailimage',
            options={'ordering': ('index', '-created_at')},
        ),
        migrations.AddField(
            model_name='productdetailimage',
            name='index',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Index'),
        ),
    ]
