# Generated by Django 5.0 on 2023-12-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GZY', '0014_alter_productdetailimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetailimage',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Visible'),
        ),
    ]
