# Generated by Django 5.0 on 2023-12-20 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GZY', '0015_productdetailimage_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GZY.productcategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='productdetailimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detail_images', to='GZY.product', verbose_name='Product'),
        ),
    ]
