# Generated by Django 5.0 on 2023-12-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GZY', '0019_product_spec'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompage',
            name='banner_hidden',
            field=models.BooleanField(default=False, verbose_name='Banner Hidden'),
        ),
    ]
