# Generated by Django 5.0 on 2023-12-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GZY', '0020_custompage_banner_hidden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-power', '-created_at')},
        ),
        migrations.AddField(
            model_name='product',
            name='power',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Power of sort'),
        ),
    ]
