# Generated by Django 5.0 on 2023-12-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GZY', '0021_alter_product_options_product_power'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Alter Text')),
                ('url', models.URLField(verbose_name='Image URL')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
