# Generated by Django 5.0 on 2023-12-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GZY', '0022_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompage',
            name='show_in_index',
            field=models.BooleanField(default=False, verbose_name='Show in homepage'),
        ),
    ]
