# Generated by Django 5.0 on 2023-12-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GZY', '0024_product_show_in_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompage',
            name='raw_content',
            field=models.TextField(blank=True, null=True, verbose_name='Raw Content'),
        ),
    ]
