on:
  push:
    branches:
      - main
jobs:
  pull:
    name: pull new code
    runs-on: ubuntu-20.04
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: cd ~/gzy-backend && git pull
